language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip 
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b pie https://github.com/iamsaalim/android_kernel_xiaomi_vince-4.9 vince
  - cd $HOME/vince
  - git push -q https://$GITHUB_TOKEN@github.com/iamsaalim/kernel_xiaomi_vince.git HEAD:4.9
