language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip 
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone https://github.com/archie9211/android_kernel_realme_RMX1801.git kernel
  - cd $HOME/kernel && git remote rm origin
  - git remote add origin https://github.com/iamsaalim/kernel_asus_X00P-research.git
  - git push -q https://$GITHUB_TOKEN@github.com/iamsaalim/kernel_realme_sdm660.git HEAD:pie

