language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip 
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b yukina-q https://github.com/Nicklas373/kernel_xiaomi_lavender.git kernel
  - cd $HOME/kernel && git remote rm origin
  - git remote add origin https://github.com/iamsaalim/kernel_asus_X00P-research.git
  - git push -q https://$GITHUB_TOKEN@github.com/iamsaalim/kernel_xiaomi_sdm660.git HEAD:OC
