language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b ten https://github.com/PixelExperience-Devices/kernel_xiaomi_sm6150.git kernel
  - cd $HOME && mkdir android && cd android
  - git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang
  - git clone --depth=1 https://github.com/arter97/arm64-gcc gcc
  - git clone --depth=1 https://github.com/arter97/arm32-gcc gcc32
  - cd $HOME/kernel && wget https://raw.githubusercontent.com/iamsaalim/script/master/kernel/violet_kernel.sh
  - chmod +x violet_kernel.sh && bash violet_kernel.sh  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: $HOME/out/arch/arm64/boot/*gz

  on:
    tags: false
    repo: iamsaalim/kernel_script
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
