language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip 
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b jasmine-p-oss https://github.com/android-linux-stable/jasmine.git kernel
  - cd $HOME/kernel 
  - git push -q https://$GITHUB_TOKEN@github.com/stormbreaker-project/kernel_xiaomi_jasmine HEAD:pie
