language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git zip 
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b linux-3.10.y https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/ kernel
  - cd $HOME/kernel
  - git push -q https://$GITHUB_TOKEN@github.com/iamsaalim/kernel_aio_oftp.git HEAD:linux
