language: C
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone https://github.com/raza231198/kernel_realme_sdm660.git kernel
  - cd $HOME/kernel && git remote rm origin
  - git remote add origin https://github.com/iamsaalim/kernel_realme_sdm660.git
  - git push -q https://$GITHUB_TOKEN@github.com/iamsaalim/kernel_realme_sdm660.git HEAD:master
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: $HOME/out/arch/arm64/boot/*gz

  on:
    tags: false
    repo: iamsaalim/kernel_script
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
